pipeline {
  agent any
  stages {
    stage('Scan') {
      steps {
        withSonarQubeEnv(installationName: 'sq1') { 
          sh 'mvn dependency:resolve'
          sh  'mvn clean deploy sonar:sonar'
        }
      }
    }
  }
}
